### ISSUE TITLE
new idea

### ISSUE THREAD

**Issue by Peta-T** [horizon-eda/horizon-docs-cz#1]
sorry but now I have idea change directory structure like this
horizon-eda/horizon-docs-cz/
drwxr-xr-x  4 petat petat    4096 lis 16 13:37 .
drwxr-xr-x 50 petat petat    4096 lis 16 09:22 ..
drwxr-xr-x  8 petat petat    4096 lis 16 14:16 .git
-rw-r--r--  1 petat petat 1181269 lis 16 13:08 horizon-eda-cz.pdf
drwxr-xr-x  4 petat petat    4096 lis 16 13:36 srcdoc

horizon-eda/horizon-docs-cz/srcdoc/
drwxr-xr-x 4 petat petat  4096 lis 16 13:36 .
drwxr-xr-x 4 petat petat  4096 lis 16 13:37 ..
-rw------- 1 petat petat  1446 lis 16 09:28 backannotation_cz.rst
drwxr-xr-x 4 petat petat  4096 lis 16 13:05 _build
-rw------- 1 petat petat  2759 lis 10 18:39 build-linux_cz.rst
-rw------- 1 petat petat  2892 lis 11 18:54 build-win32_cz.rst
-rw------- 1 petat petat  1910 lis 11 18:55 cli-usage_cz.rst
-rw------- 1 petat petat  5284 lis 16 10:02 conf.py
-rw------- 1 petat petat  2729 lis 10 18:50 copy-layout-placement_cz.rst
-rw------- 1 petat petat  5135 lis 16 09:56 create-package_cz.rst
-rw------- 1 petat petat  2759 lis 11 19:18 feature-overview_cz.rst
-rw------- 1 petat petat  3528 lis 16 09:57 getting-started_cz.rst
-rwxr-xr-x 1 petat petat   120 lis 16 10:01 go.sh
drwxr-xr-x 2 petat petat  4096 říj 22 22:14 images
-rw------- 1 petat petat  1810 lis 16 09:57 imp-board_cz.rst
-rw------- 1 petat petat  1661 říj  7 21:51 imp_cz.rst
-rw------- 1 petat petat  3827 lis 16 09:58 imp-sch_cz.rst
-rw------- 1 petat petat   597 lis 16 09:59 index.rst
-rw------- 1 petat petat 20133 říj  7 21:51 LICENSE.txt
-rw------- 1 petat petat   581 říj  7 21:51 Makefile
-rw------- 1 petat petat  1539 lis 16 09:59 padstacks_cz.rst
-rw------- 1 petat petat  4096 lis 10 19:18 parameter-programs_cz.rst
-rw------- 1 petat petat  4978 lis 16 10:00 pool_cz.rst
-rw------- 1 petat petat  7973 lis 16 10:00 pool-mgr_cz.rst
-rw------- 1 petat petat   476 lis 16 09:49 README.md
-rw------- 1 petat petat   429 lis 10 19:28 rules_cz.rst
-rw------- 1 petat petat  1914 říj 22 18:02 theory-of-operation_cz.rst

can you remove all files?
Thanks

**Comment by carrotIndustries** [comment]
can't you force-push to this repo?

regarding the directory structure: I'm to sure if readthedocs works wit the index.rst not being in the root directory, please check this first.

**Comment by Peta-T** [comment]
Thanks, now its look better.
